name: Build Mod

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Clean Gradle cache (IMPORTANT FIX)
        run: |
          rm -rf ~/.gradle
          rm -rf .gradle

      - name: Grant permission
        run: chmod +x gradlew

      - name: Verify Gradle version
        run: ./gradlew --version

      - name: Build
        run: ./gradlew build

      - name: Upload Mod
        uses: actions/upload-artifact@v4
        with:
          name: hotbargrid-mod
          path: build/libs/*.jar
